// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intersect.Server.Migrations.Sqlite.Game
{
    [DbContext(typeof(Intersect.Server.Database.GameData.SqliteGameContext))]
    [Migration("20260107000000_AddAnimationFrameSpeed")]
    partial class AddAnimationFrameSpeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Intersect.Framework.Core.GameObjects.Items.ItemDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnimationFrameSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AnimationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("Animation");

                    // ... (other properties will be inherited from snapshot logic if this file is just the migration designer)
                });
#pragma warning restore 612, 618
        }
    }
}
